### ISSUE TITLE
Register and set proper meta fields

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/media-experiments#222]
Existing:

* [x] `mexp_blurhash`
* [x] `mexp_dominant_color`
* [x] `mexp_generated_poster_id`
* [x] `mexp_is_muted`

New:

* [x] `mexp_is_gif` - Whether the video is to be considered a GIF (looping, muted, GIF variation)
   * Useful for automatically transforming a video block into a GIF variation upon insertion of such an attachment.
   * Can be passed during upload
* [x] `mexp_optimized_id` - ID of optimized image/video (to be set on the original attachment)
	* Can be added to the original after successful upload either client-side or server-side.
	* If an attachment has this, do not re-optimize it but instead just fetch the optimized entity record.
* [x] `mexp_original_id` - ID of original attachment (to be set on the optimized attachment)
	* Not using `parent` relationship because ideally the optimized attachment's parent is the same post as the original's.
    * Can be passed during upload.

**Comment by swissspidy** [comment]
> `mexp_is_gif`

This can actually be achieved through the `gif-conversion` `mexp_media_source` term
